export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const POST_JOB = "POST_JOB";
export const POST_JOB_DELETE = "POST_JOB_DELETE";
export const APPLY_JOBS = "APPLY_JOBS";
